# Generated by Django 4.1.2 on 2022-12-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='subject_total_marks',
            field=models.FloatField(default=0),
        ),
    ]
